services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      - database_hostname=db
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=admin
    ports:
      - 5432:5432

  pgadmin:
    profiles:
      - dev
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@cleanarch.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - 5050:80
